#!/usr/bin/perl -w
# 

use strict;
use utf8;
use FileHandle;
use IPC::Open2;
use Env qw( LC_CTYPE DISPLAY SSH_TTY );

my $arg = shift(@ARGV);

# open pinentry
my $pid = "";
if ( defined($DISPLAY) && !defined($SSH_TTY) ) {
	$pid = open2(*IN, *OUT, "pinentry-x11 -g") || die;
} else {
	# get a tty
	open F, "tty |" || die ("can't fork to tty");
	my $tty = <F>;
	close F;
	$pid = open2(*IN, *OUT, "pinentry-curses --ttyname $tty") || die;
}

my $lctype = "en_US.UTF-8";
if ( defined($LC_CTYPE) ) {
	$lctype = $LC_CTYPE;
}
print OUT "OPTION lc-ctype=$lctype\n";

############################################################################
sub getpass($) {
	my $prompt = shift;
	print OUT "SETDESC LUKS Passphrase\nSETPROMPT $prompt\nGETPIN\n";
	while ( <IN> ) {
		if ( /^OK/ ) { 
			next;
		} elsif ( /^ERR \d+ (.*)/ ) {
			print STDERR $1."\n";
			exit 1;
			last;
		} elsif ( /^D (.*)/ ) {
			return $1;
		}
	}
}

if ( defined($arg) &&  $arg eq "invalid" ) {
	print OUT "SETERROR Invalid Passphrase, try again\n";
}

my $p = getpass("Enter LUKS Passphrase");
if ( defined($arg) &&  $arg eq "confirm" ) {
	while ( $p ne getpass("Confirm LUKS Passphrase") ) {
		print OUT "SETDESC Passhphrases do not match\nMESSAGE\n";
		$p = getpass("Re-Enter LUKS passphrase");
	}
}

print "$p";
